spring:
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework: INFO
    br.com.ffroliva.mimecast: DEBUG


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    parser:
      STRICT_DUPLICATE_DETECTION: true

#Propriedades Documentação
app:
  documentation:
    version: '@project.version@'
    title: File Search Rest API
    description: '@project.description@'

  servers: http://localhost:8080, http://localhost:9090
  proxy-url: http://localhost:8080
  frontend: /swagger-ui.html
